######################################################################
# Automatically generated by qmake (2.01a) Sat May 4 02:31:27 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
