######################################################################
# Automatically generated by qmake (1.07a) Mon Jan 6 10:31:23 2014
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += ipctrl.h
INTERFACES += mainwindow.ui
SOURCES += ipctrl.cpp main.cpp
