######################################################################
# Automatically generated by qmake (2.01a) ?? 1? 6 10:16:39 2014
######################################################################


QT       += core gui

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TARGET = ip
TEMPLATE = app


SOURCES += ipctrl.cpp main.cpp

HEADERS  += ipctrl.h
