FileReloader.o: FileReloader.cpp FileReloader.h \
 bsl/containers/string/bsl_string.h
ConfigReloader.o: ConfigReloader.cpp ConfigReloader.h Configure.h \
 ConfigGroup.h ConfigUnit.h utils/cc_utils.h utils/cc_exception.h \
 utils/cc_struct.h bsl/containers/string/bsl_string.h \
 bsl/exception/bsl_exception.h ul_error.h utils/cc_log.h ul_log.h \
 utils/cc_trans.h bsl/var/IVar.h bsl/var/Ref.h bsl/ResourcePool.h \
 ConfigError.h
CmdOption.o: CmdOption.cpp CmdOption.h ConfigGroup.h ConfigUnit.h \
 utils/cc_utils.h utils/cc_exception.h utils/cc_struct.h \
 bsl/containers/string/bsl_string.h bsl/exception/bsl_exception.h \
 ul_error.h utils/cc_log.h ul_log.h utils/cc_trans.h bsl/var/IVar.h \
 bsl/var/Ref.h bsl/ResourcePool.h ConfigError.h
ConfigError.o: ConfigError.cpp ConfigError.h utils/cc_utils.h \
 utils/cc_exception.h utils/cc_struct.h \
 bsl/containers/string/bsl_string.h bsl/exception/bsl_exception.h \
 ul_error.h utils/cc_log.h ul_log.h utils/cc_trans.h ConfigUnit.h \
 bsl/var/IVar.h bsl/var/Ref.h bsl/ResourcePool.h
ConfigGroup.o: ConfigGroup.cpp ConfigGroup.h ConfigUnit.h \
 utils/cc_utils.h utils/cc_exception.h utils/cc_struct.h \
 bsl/containers/string/bsl_string.h bsl/exception/bsl_exception.h \
 ul_error.h utils/cc_log.h ul_log.h utils/cc_trans.h bsl/var/IVar.h \
 bsl/var/Ref.h bsl/ResourcePool.h ConfigError.h ConfigArray.h \
 bsl/var/Array.h Configure.h bsl/var/Dict.h
ConfigUnit.o: ConfigUnit.cpp ConfigUnit.h utils/cc_utils.h \
 utils/cc_exception.h utils/cc_struct.h \
 bsl/containers/string/bsl_string.h bsl/exception/bsl_exception.h \
 ul_error.h utils/cc_log.h ul_log.h utils/cc_trans.h bsl/var/IVar.h \
 bsl/var/Ref.h bsl/ResourcePool.h ConfigError.h ConfigArray.h \
 ConfigGroup.h bsl/var/Array.h reader/Reader.h reader/RawData.h \
 utils/cc_exception.h utils/cc_log.h Configure.h ConfigGroup.h \
 bsl/var/String.h
Configure.o: Configure.cpp Configure.h ConfigGroup.h ConfigUnit.h \
 utils/cc_utils.h utils/cc_exception.h utils/cc_struct.h \
 bsl/containers/string/bsl_string.h bsl/exception/bsl_exception.h \
 ul_error.h utils/cc_log.h ul_log.h utils/cc_trans.h bsl/var/IVar.h \
 bsl/var/Ref.h bsl/ResourcePool.h ConfigError.h reader/Reader.h \
 reader/RawData.h utils/cc_exception.h utils/cc_log.h Configure.h \
 constraint/Constraint.h constraint/ConstraintFunction.h ConfigGroup.h \
 ConfigUnit.h compiler/src/idl_conf_if.h bsl/var/Dict.h bsl/var/Array.h
Constraint.o: constraint/Constraint.cpp constraint/Constraint.h \
 Configure.h ConfigGroup.h ConfigUnit.h utils/cc_utils.h \
 utils/cc_exception.h utils/cc_struct.h \
 bsl/containers/string/bsl_string.h bsl/exception/bsl_exception.h \
 ul_error.h utils/cc_log.h ul_log.h utils/cc_trans.h bsl/var/IVar.h \
 bsl/var/Ref.h bsl/ResourcePool.h ConfigError.h \
 constraint/ConstraintFunction.h ConfigGroup.h ConfigUnit.h \
 utils/cc_utils.h compiler/src/idl_conf_if.h
ConstraintFunction.o: constraint/ConstraintFunction.cpp \
 constraint/ConstraintFunction.h Configure.h ConfigGroup.h ConfigUnit.h \
 utils/cc_utils.h utils/cc_exception.h utils/cc_struct.h \
 bsl/containers/string/bsl_string.h bsl/exception/bsl_exception.h \
 ul_error.h utils/cc_log.h ul_log.h utils/cc_trans.h bsl/var/IVar.h \
 bsl/var/Ref.h bsl/ResourcePool.h ConfigError.h ConfigGroup.h \
 ConfigUnit.h constraint/cc_default.h constraint/Constraint.h \
 compiler/src/idl_conf_if.h
cc_default.o: constraint/cc_default.cpp constraint/cc_default.h \
 constraint/Constraint.h Configure.h ConfigGroup.h ConfigUnit.h \
 utils/cc_utils.h utils/cc_exception.h utils/cc_struct.h \
 bsl/containers/string/bsl_string.h bsl/exception/bsl_exception.h \
 ul_error.h utils/cc_log.h ul_log.h utils/cc_trans.h bsl/var/IVar.h \
 bsl/var/Ref.h bsl/ResourcePool.h ConfigError.h \
 constraint/ConstraintFunction.h ConfigGroup.h ConfigUnit.h \
 compiler/src/idl_conf_if.h utils/cc_utils.h ConfigArray.h \
 bsl/var/Array.h spreg.h
RawData.o: reader/RawData.cpp reader/RawData.h utils/cc_exception.h \
 utils/cc_struct.h bsl/containers/string/bsl_string.h \
 bsl/exception/bsl_exception.h ul_error.h utils/cc_log.h ul_log.h
Reader.o: reader/Reader.cpp utils/cc_utils.h utils/cc_exception.h \
 utils/cc_struct.h bsl/containers/string/bsl_string.h \
 bsl/exception/bsl_exception.h ul_error.h utils/cc_log.h ul_log.h \
 utils/cc_trans.h reader/Reader.h reader/RawData.h utils/cc_exception.h \
 utils/cc_log.h Configure.h ConfigGroup.h ConfigUnit.h utils/cc_utils.h \
 bsl/var/IVar.h bsl/var/Ref.h bsl/ResourcePool.h ConfigError.h
init.o: utils/init.cpp utils/cc_log.h ul_log.h
trans.o: utils/trans.cpp utils/cc_utils.h utils/cc_exception.h \
 utils/cc_struct.h bsl/containers/string/bsl_string.h \
 bsl/exception/bsl_exception.h ul_error.h utils/cc_log.h ul_log.h \
 utils/cc_trans.h
cfgext.o: cfgext.cpp cfgext.h utils/cc_utils.h utils/cc_exception.h \
 utils/cc_struct.h bsl/containers/string/bsl_string.h \
 bsl/exception/bsl_exception.h ul_error.h utils/cc_log.h ul_log.h \
 utils/cc_trans.h compiler/src/idl_conf_if.h Configure.h ConfigGroup.h \
 ConfigUnit.h bsl/var/IVar.h bsl/var/Ref.h bsl/ResourcePool.h \
 ConfigError.h
cfgflag.o: cfgflag.cpp cfgflag.h Configure.h ConfigGroup.h ConfigUnit.h \
 utils/cc_utils.h utils/cc_exception.h utils/cc_struct.h \
 bsl/exception/bsl_exception.h ul_error.h utils/cc_log.h ul_log.h \
 utils/cc_trans.h bsl/var/IVar.h bsl/var/Ref.h bsl/ResourcePool.h \
 ConfigError.h CmdOption.h cfgext.h
idl.o: compiler/src/idl.c compiler/src/idl_conf_if.h \
 bsl/containers/string/bsl_string.h compiler/src/idl.h \
 compiler/src/idl_lex.h
idl_lex.o: compiler/src/idl_lex.c compiler/src/idl.h \
 compiler/src/idl_conf_if.h bsl/containers/string/bsl_string.h \
 compiler/src/idl_gram.h
idl_gram.o: compiler/src/idl_gram.c compiler/src/idl.h \
 compiler/src/idl_conf_if.h bsl/containers/string/bsl_string.h \
 compiler/src/idl_gram.h compiler/src/idl_lex.h
