// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: idl.proto

#ifndef PROTOBUF_idl_2eproto__INCLUDED
#define PROTOBUF_idl_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_idl_2eproto();
void protobuf_AssignDesc_idl_2eproto();
void protobuf_ShutdownFile_idl_2eproto();

class CommonMsg;

// ===================================================================

class CommonMsg : public ::google::protobuf::Message {
 public:
  CommonMsg();
  virtual ~CommonMsg();

  CommonMsg(const CommonMsg& from);

  inline CommonMsg& operator=(const CommonMsg& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CommonMsg& default_instance();

  void Swap(CommonMsg* other);

  // implements Message ----------------------------------------------

  CommonMsg* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CommonMsg& from);
  void MergeFrom(const CommonMsg& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 obj_id = 1;
  inline bool has_obj_id() const;
  inline void clear_obj_id();
  static const int kObjIdFieldNumber = 1;
  inline ::google::protobuf::uint32 obj_id() const;
  inline void set_obj_id(::google::protobuf::uint32 value);

  // required uint32 obj_op = 2;
  inline bool has_obj_op() const;
  inline void clear_obj_op();
  static const int kObjOpFieldNumber = 2;
  inline ::google::protobuf::uint32 obj_op() const;
  inline void set_obj_op(::google::protobuf::uint32 value);

  // required uint32 version = 3;
  inline bool has_version() const;
  inline void clear_version();
  static const int kVersionFieldNumber = 3;
  inline ::google::protobuf::uint32 version() const;
  inline void set_version(::google::protobuf::uint32 value);

  // required uint32 reserved = 4;
  inline bool has_reserved() const;
  inline void clear_reserved();
  static const int kReservedFieldNumber = 4;
  inline ::google::protobuf::uint32 reserved() const;
  inline void set_reserved(::google::protobuf::uint32 value);

  // required string str = 5;
  inline bool has_str() const;
  inline void clear_str();
  static const int kStrFieldNumber = 5;
  inline const ::std::string& str() const;
  inline void set_str(const ::std::string& value);
  inline void set_str(const char* value);
  inline void set_str(const char* value, size_t size);
  inline ::std::string* mutable_str();
  inline ::std::string* release_str();
  inline void set_allocated_str(::std::string* str);

  // @@protoc_insertion_point(class_scope:CommonMsg)
 private:
  inline void set_has_obj_id();
  inline void clear_has_obj_id();
  inline void set_has_obj_op();
  inline void clear_has_obj_op();
  inline void set_has_version();
  inline void clear_has_version();
  inline void set_has_reserved();
  inline void clear_has_reserved();
  inline void set_has_str();
  inline void clear_has_str();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 obj_id_;
  ::google::protobuf::uint32 obj_op_;
  ::google::protobuf::uint32 version_;
  ::google::protobuf::uint32 reserved_;
  ::std::string* str_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(5 + 31) / 32];

  friend void  protobuf_AddDesc_idl_2eproto();
  friend void protobuf_AssignDesc_idl_2eproto();
  friend void protobuf_ShutdownFile_idl_2eproto();

  void InitAsDefaultInstance();
  static CommonMsg* default_instance_;
};
// ===================================================================


// ===================================================================

// CommonMsg

// required uint32 obj_id = 1;
inline bool CommonMsg::has_obj_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CommonMsg::set_has_obj_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CommonMsg::clear_has_obj_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CommonMsg::clear_obj_id() {
  obj_id_ = 0u;
  clear_has_obj_id();
}
inline ::google::protobuf::uint32 CommonMsg::obj_id() const {
  return obj_id_;
}
inline void CommonMsg::set_obj_id(::google::protobuf::uint32 value) {
  set_has_obj_id();
  obj_id_ = value;
}

// required uint32 obj_op = 2;
inline bool CommonMsg::has_obj_op() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void CommonMsg::set_has_obj_op() {
  _has_bits_[0] |= 0x00000002u;
}
inline void CommonMsg::clear_has_obj_op() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void CommonMsg::clear_obj_op() {
  obj_op_ = 0u;
  clear_has_obj_op();
}
inline ::google::protobuf::uint32 CommonMsg::obj_op() const {
  return obj_op_;
}
inline void CommonMsg::set_obj_op(::google::protobuf::uint32 value) {
  set_has_obj_op();
  obj_op_ = value;
}

// required uint32 version = 3;
inline bool CommonMsg::has_version() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void CommonMsg::set_has_version() {
  _has_bits_[0] |= 0x00000004u;
}
inline void CommonMsg::clear_has_version() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void CommonMsg::clear_version() {
  version_ = 0u;
  clear_has_version();
}
inline ::google::protobuf::uint32 CommonMsg::version() const {
  return version_;
}
inline void CommonMsg::set_version(::google::protobuf::uint32 value) {
  set_has_version();
  version_ = value;
}

// required uint32 reserved = 4;
inline bool CommonMsg::has_reserved() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void CommonMsg::set_has_reserved() {
  _has_bits_[0] |= 0x00000008u;
}
inline void CommonMsg::clear_has_reserved() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void CommonMsg::clear_reserved() {
  reserved_ = 0u;
  clear_has_reserved();
}
inline ::google::protobuf::uint32 CommonMsg::reserved() const {
  return reserved_;
}
inline void CommonMsg::set_reserved(::google::protobuf::uint32 value) {
  set_has_reserved();
  reserved_ = value;
}

// required string str = 5;
inline bool CommonMsg::has_str() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void CommonMsg::set_has_str() {
  _has_bits_[0] |= 0x00000010u;
}
inline void CommonMsg::clear_has_str() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void CommonMsg::clear_str() {
  if (str_ != &::google::protobuf::internal::kEmptyString) {
    str_->clear();
  }
  clear_has_str();
}
inline const ::std::string& CommonMsg::str() const {
  return *str_;
}
inline void CommonMsg::set_str(const ::std::string& value) {
  set_has_str();
  if (str_ == &::google::protobuf::internal::kEmptyString) {
    str_ = new ::std::string;
  }
  str_->assign(value);
}
inline void CommonMsg::set_str(const char* value) {
  set_has_str();
  if (str_ == &::google::protobuf::internal::kEmptyString) {
    str_ = new ::std::string;
  }
  str_->assign(value);
}
inline void CommonMsg::set_str(const char* value, size_t size) {
  set_has_str();
  if (str_ == &::google::protobuf::internal::kEmptyString) {
    str_ = new ::std::string;
  }
  str_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* CommonMsg::mutable_str() {
  set_has_str();
  if (str_ == &::google::protobuf::internal::kEmptyString) {
    str_ = new ::std::string;
  }
  return str_;
}
inline ::std::string* CommonMsg::release_str() {
  clear_has_str();
  if (str_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = str_;
    str_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void CommonMsg::set_allocated_str(::std::string* str) {
  if (str_ != &::google::protobuf::internal::kEmptyString) {
    delete str_;
  }
  if (str) {
    set_has_str();
    str_ = str;
  } else {
    clear_has_str();
    str_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_idl_2eproto__INCLUDED
