######################################################################
# Automatically generated by qmake (2.01a) Tue Jan 7 14:27:08 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ipctrl.h mainwindow.h
FORMS += mainwindow.ui
SOURCES += ipctrl.cpp main.cpp mainwindow.cpp
