######################################################################
# Automatically generated by qmake (2.01a) Fri Feb 14 10:47:24 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h qcustomplot.h
FORMS += mainwindow.ui
SOURCES += main.cpp mainwindow.cpp qcustomplot.cpp
