######################################################################
# Automatically generated by qmake (2.01a) Thu Jan 16 11:39:11 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += base.h MyThread.h
SOURCES += base.cpp main.cpp MyThread.cpp
