######################################################################
# Automatically generated by qmake (2.01a) Tue Feb 11 17:01:12 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += screenshot.h
SOURCES += main.cpp screenshot.cpp
